repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.16
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright src/
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.11.0.1"
    hooks:
      - id: shellcheck
